FLPG-166: support orgId from query params
FrontlineEducation/passport-identityserver3 pull request #8
Opened 2018-07-10 21:23 UTC by nbyrd

**Story/Card:**

[FLPG-166](https://frontlinetechnologies.atlassian.net/browse/FLPG-166)

**What does this PR do?**
This change detects whether org_id is specified in the request query parameters. Iff so, we pass that along as an ACR key-value pair to IDM so that it can react appropriately.

**Where should reviewer start?**
Consider that links sent out by e-mail for C&C will soon include the user's org-id as a query param ("org_id", specifically). This code should be able to pick that out and run with it.

**Image showing how you feel about this PR [click here for giphy]:(http://giphy.com)**
https://i.imgur.com/T8dvYWH.mp4

2018-07-10 21:30 UTC, FLAHORAK requested changes
rather than hard code the dependency on orgId, I think I would let this middleware take a function with `req` as the parameter at configuration time.  

it could return an array of acr_values that would then union with the static config acr_values, as an example.   that keeps specific knowledge about what query params and what not out of the generic auth library.

2018-07-10 23:12 UTC, nbyrd commented
@FLAHORAK Please see updated code, according to your review comment.

2018-07-10 23:19 UTC, el-besto commented on strategy.js
> +        config.acr_appenders = config.acr_appenders.splice();
Do you mean to use .slice here too? Splice will modify the original array I believe.

2018-07-11 23:54 UTC, theryanngai approved these changes

2018-07-16 23:05 UTC, FLAHORAK approved these changes

2018-07-18 20:13 UTC, merged